export const courseBase = '/training/confident-with-ai';

export type CoursePage = {
  slug: string;
  number?: number;
  part: string;
  title: string;
  summary: string;
  outcome: string;
  ideas: string[];
  activity: string;
  checkpoint: string;
  caution?: string;
  estimatedMinutes?: number;
  reviewed?: string;
};

export const modules: CoursePage[] = [
  { slug: '01-start-here', number: 1, part: 'Start here', title: 'Start Here: Your First Five Minutes with AI', summary: 'Open an AI assistant and get your first useful result.', outcome: 'By the end, you will have asked an assistant for something useful and improved its first answer.', ideas: ['An AI assistant responds to ordinary language. You do not need special commands.', 'Treat its answer as a draft or estimate, not proof.', 'You can ask follow-up questions: the conversation is part of the tool.'], activity: 'Open www.chat.com. Find the message box and ask the assistant to explain something you already understand. If you cannot think of a subject, ask: “Explain why we have seasons.” When it replies, say: “Make that shorter and give me one example.”', checkpoint: 'You can describe one useful thing the assistant did and one reason you would still use your own judgement.', caution: 'Do not enter private, confidential or identifying information during this exercise.', estimatedMinutes: 5 },
  { slug: '02-choose-an-ai-assistant', number: 2, part: 'Part One: Begin Using AI', title: 'Choose an AI Assistant', summary: 'Choose an accessible, affordable place to begin.', outcome: 'By the end, you will have chosen one assistant to try without treating the choice as permanent.', ideas: ['Begin with the service that is easiest to access on your device.', 'Free access is enough for this course.', 'Assistant names, prices and features change, so current product comparisons belong in Tool Cards.'], activity: 'Open one general AI assistant and check that you can find the message box, send a message and read the response with your preferred access method.', checkpoint: 'You can name the assistant you will start with and confirm that its basic conversation works for you.', caution: 'Do not paste private, confidential or identifying information while testing.' },
  { slug: '03-first-useful-conversation', number: 3, part: 'Part One: Begin Using AI', title: 'Have Your First Useful Conversation', summary: 'Improve an answer by adding purpose, context and the form you need.', outcome: 'By the end, you will be able to improve an answer through follow-up rather than starting again.', ideas: ['Say what you are trying to achieve.', 'Give only the context that changes the answer.', 'Ask for a useful form: steps, short explanation, comparison or draft.', 'Correct the assistant and continue the same conversation.'], activity: 'Ask for help with a real low-stakes task. Add your purpose, one relevant detail and the form you want. Then request one revision.', checkpoint: 'The revised response is more useful to you, and you can identify which extra instruction improved it.' },
  { slug: '04-everyday-things-ai-can-do', number: 4, part: 'Part One: Begin Using AI', title: 'Everyday Things AI Can Help You Do', summary: 'Use AI to explain, summarise, draft, compare, plan and brainstorm.', outcome: 'By the end, you will have matched a real task to an appropriate kind of AI help.', ideas: ['Good starting tasks include drafting, rewriting, explaining and brainstorming.', 'AI can help prepare questions without making the final decision.', 'A useful answer should reduce work or open access, not create more checking than it saves.'], activity: 'Choose one small task you would otherwise postpone. Ask for a first draft, plan or explanation, then edit the result yourself.', checkpoint: 'You have a usable result and can say what work remained yours.' },
  { slug: '05-know-what-you-are-holding', number: 5, part: 'Part Two: Judge What AI Gives You', title: 'Know What You Are Holding', summary: 'Learn why a polished AI response is not proof.', outcome: 'By the end, you will be able to explain “answer-shaped object” in ordinary language.', ideas: ['AI produces language with the shape of an answer; polish does not guarantee truth.', 'An estimate can still be valuable when the alternative is no accessible route into a subject.', 'Human context and judgement are load-bearing.'], activity: 'Take one confident AI answer and mark which parts are facts, suggestions, estimates or things you cannot yet classify.', checkpoint: 'You can explain why the answer may be useful without calling it knowledge or dismissing it as worthless.' },
  { slug: '06-what-happens-if-it-is-wrong', number: 6, part: 'Part Two: Judge What AI Gives You', title: 'What Happens If It Is Wrong?', summary: 'Use green, amber and red risk bands to decide how much checking is needed.', outcome: 'By the end, you will be able to match the stakes of a task to a checking level.', ideas: ['Green: a mistake is easy to notice and cheap to fix.', 'Amber: you want it right, so check important details.', 'Red: health, money, law, safety or serious consequences require authoritative or qualified help.'], activity: 'Classify three recent questions as green, amber or red. State what you would check in each case.', checkpoint: 'Your checking effort increases with the harm a wrong answer could cause.', caution: 'AI can help you understand a high-stakes issue or prepare questions; it should not be the final authority.' },
  { slug: '07-check-an-answer', number: 7, part: 'Part Two: Judge What AI Gives You', title: 'Check an Answer Without Becoming an Expert', summary: 'Check sources, dates, numbers and important claims.', outcome: 'By the end, you will be able to verify the part of an answer that carries the most weight.', ideas: ['Ask for sources, then open them: a citation is not verification.', 'Check that the source supports the exact claim and is current enough.', 'Compare independent sources and use qualified help when the stakes demand it.'], activity: 'Choose one factual claim. Find the original or authoritative source, check its date and write one sentence saying what it actually supports.', checkpoint: 'You can show the source and distinguish what it confirms from what remains uncertain.' },
  { slug: '08-choose-an-image-tool', number: 8, part: 'Part Three: Understand Images and Visual Information', title: 'Choose the Right Kind of Image Tool', summary: 'Match quick description, exact recognition, private processing or human help to the job.', outcome: 'By the end, you will choose a tool category from the information and risk involved.', ideas: ['Conversational description is useful for scenes and exploration.', 'Text recognition and document tools are better for exact wording and structure.', 'Use private processing or human verification when sensitivity or consequence requires it.'], activity: 'For a photograph, bank letter and medicine label, choose a tool category and explain why.', checkpoint: 'Your choice changes when exact text, privacy or consequences change.' },
  { slug: '09-ask-for-an-image-description', number: 9, part: 'Part Three: Understand Images and Visual Information', title: 'Ask for the Description You Need', summary: 'Request an overview, literal facts, visible text, layout or atmosphere.', outcome: 'By the end, you will be able to ask for a description fitted to your purpose.', ideas: ['Start with your purpose: identification, navigation, appreciation, publication or checking.', 'Ask separately for visible text, positions and uncertain details.', 'Request literal facts before interpretation when accuracy matters.'], activity: 'Use one image and request two descriptions: a brief overview and a detailed literal account with all visible text.', checkpoint: 'The two descriptions differ in useful ways because your requests were specific.' },
  { slug: '10-check-an-image-description', number: 10, part: 'Part Three: Understand Images and Visual Information', title: 'Judge and Double-Check an Image Description', summary: 'Separate visible facts, context, interpretation and unsupported guesses.', outcome: 'By the end, you will be able to identify which details need a second check.', ideas: ['Names are harder than kinds; exact counts and positions are fragile.', 'A model may state an interpretation with the texture of a visible fact.', 'Narrow questions and a second independent description can expose drift.'], activity: 'Ask a model to label each statement in its description as visible, inferred, contextual or uncertain. Recheck the most important claim separately.', checkpoint: 'You can name the important detail, its evidence category and how you checked it.' },
  { slug: '11-read-documents-forms-and-screenshots', number: 11, part: 'Part Three: Understand Images and Visual Information', title: 'Read Documents, Forms and Screenshots', summary: 'Recover exact text and structure from visual documents.', outcome: 'By the end, you will be able to request text, reading order and form structure separately.', ideas: ['Ask for verbatim text before summary.', 'Request headings, labels, fields, checked states and reading order.', 'Poor images, handwriting and inaccessible PDFs may require another tool or human help.'], activity: 'Use a non-sensitive document image. Ask for exact text, then a structural outline, then a list of uncertain characters or fields.', checkpoint: 'You can reconstruct the document without silently treating uncertain text as exact.' },
  { slug: '12-understand-tables-charts-and-slides', number: 12, part: 'Part Three: Understand Images and Visual Information', title: 'Understand Tables, Charts and Slides', summary: 'Recover data structure, labels, order and values.', outcome: 'By the end, you will be able to ask for a structured representation before an interpretation.', ideas: ['For tables, request column headings and each row in a consistent order.', 'For charts, ask for title, axes, units, legend, values and trend separately.', 'For slides, preserve slide order, headings, body text and speaker meaning.'], activity: 'Take one table, chart or slide. Ask first for its structure and values, then for a short interpretation that identifies uncertainty.', checkpoint: 'You can trace every important conclusion back to a label or value in the structured account.' },
  { slug: '13-create-your-first-image', number: 13, part: 'Part Four: Create Visual Media', title: 'Create Your First Image', summary: 'Write a brief, generate an image, describe it back and revise once.', outcome: 'By the end, you will have made one deliberate visual revision based on evidence.', ideas: ['State what the image must communicate, who it is for and where it will appear.', 'Describe subject, setting, composition, mood and any required text.', 'Have the result described back before deciding what to change.'], activity: 'Create a low-stakes image from a plain-language brief. Obtain a fresh description, compare it with the brief and make one specific revision.', checkpoint: 'You can name the mismatch you found and show how the revision addressed it.' },
  { slug: '14-creative-control-without-sight', number: 14, part: 'Part Four: Create Visual Media', title: 'Keep Creative Control Without Sight', summary: 'Use intention, hierarchy and proportionate review to remain the author.', outcome: 'By the end, you will be able to separate authorship from pixel-by-pixel inspection.', ideas: ['Creative control begins with intention and explicit constraints.', 'Descriptions, comparison and selective human review are instruments, not authors.', 'Spend verification on the details that carry meaning or reputational risk.'], activity: 'Write a five-line visual brief with purpose, audience, essential elements, forbidden elements and the test for success.', checkpoint: 'Another person or tool could review the result against your stated criteria without guessing your intention.' },
  { slug: '15-create-a-comic', number: 15, part: 'Part Four: Create Visual Media', title: 'Create a Comic or Visual Story', summary: 'Develop panels, dialogue and continuity, then check reading order.', outcome: 'By the end, you will have a panel plan that can be checked independently of the finished artwork.', ideas: ['Write the story beat and purpose of every panel first.', 'Keep character descriptions and visual anchors consistent.', 'Check panel order, dialogue ownership, spelling and continuity.'], activity: 'Draft a three-panel story as numbered beats. Generate or sketch it, then request a panel-by-panel description with all text transcribed.', checkpoint: 'The described sequence tells the intended story in the intended order.' },
  { slug: '16-create-animation-and-video', number: 16, part: 'Part Four: Create Visual Media', title: 'Create Animation and Video', summary: 'Plan movement, dialogue, music and sound as one sequence.', outcome: 'By the end, you will be able to specify and check a short time-based sequence.', ideas: ['Describe what changes over time, not only the starting frame.', 'Use sound as a direct creative material and as evidence of timing.', 'Check unexpected visual changes between shots or generated frames.'], activity: 'Write a ten-second sequence with timestamps for action, speech, music and sound effects. Ask for a shot-by-shot or time-coded account of the result.', checkpoint: 'The timing and story can be understood from the combined visual description and audio plan.' },
  { slug: '17-publish-visual-work-accessibly', number: 17, part: 'Part Four: Create Visual Media', title: 'Check and Publish Visual Work Accessibly', summary: 'Define finished, check proportionately and provide accessible alternatives.', outcome: 'By the end, you will be able to choose the right accessible description for a visual work.', ideas: ['Check spelling, identity, continuity, composition and essential meaning before publication.', 'Use concise alt text for purpose; use extended descriptions for detail.', 'Provide captions, transcripts or audio description when time-based media requires them.'], activity: 'Write alt text for one finished image. If the image carries more detail than concise alt text can hold, add an extended description.', checkpoint: 'A person who cannot see the work receives its purpose and essential information without redundant filler.' },
  { slug: 'models-and-open-weights', part: 'Optional Further Study', title: 'Models, Open Weights and the Changing Frontier', summary: 'Optional reading that distinguishes assistants from models and explores closed, open-weight and specialist systems.', outcome: 'By the end, you will be able to distinguish a product interface from the model or models behind it.', ideas: ['An assistant is a service; a model is an engine it may use.', 'Open-weight models permit broader inspection or local use, but “open” has several meanings.', 'This field changes quickly, so product examples must be dated.'], activity: 'Choose one assistant and find out which model it says it is using. Record the date and source of that information.', checkpoint: 'You can explain why the assistant name and model name are not interchangeable.', estimatedMinutes: 15 },
  { slug: 'philosophy-of-answer-shaped-objects', part: 'Optional Further Study', title: 'Philosophy: Knowledge, Testimony and Answer-Shaped Objects', summary: 'Optional reading about uncertainty, epistemic opacity and warranted reliance.', outcome: 'By the end, you will be able to discuss what would justify relying on an AI answer.', ideas: ['Fluency can resemble testimony without the ordinary human relation to knowledge.', 'Access to an answer is not the same as access to the means of evaluating it.', 'Reliance depends on evidence, stakes, alternatives and the recipient’s ability to check.'], activity: 'Choose an AI answer you used. Write what justified relying on it, what remained opaque and what would have changed your decision.', checkpoint: 'Your account distinguishes usefulness, truth and justified reliance.', estimatedMinutes: 15 },
];

export const toolCards: CoursePage[] = [
  ['ai-assistants', 'General AI Assistants', 'Conversation, explanation, writing, research and general assistance.'],
  ['conversational-image-description', 'Conversational Image Describers', 'Quick, natural descriptions of photographs, objects and scenes.'],
  ['text-and-document-recognition', 'Text and Document Recognition', 'Reading text, forms, documents, tables and structured information.'],
  ['multiple-model-comparison', 'Multiple-Model Comparison', 'Methods for comparing independent descriptions or answers.'],
  ['private-and-on-device-tools', 'Private and On-Device Tools', 'Local processing, offline access and greater control over information.'],
  ['human-visual-assistance', 'Human Visual-Assistance Services', 'Human verification when accuracy or judgement matters.'],
  ['image-generators', 'Image Generators', 'Creating and revising still images.'],
  ['video-and-animation-generators', 'Video and Animation Generators', 'Creating movement, animation, dialogue, music and video.'],
].map(([slug, title, summary]) => ({ slug, part: 'Tool Cards', title, summary, outcome: 'Use this card to choose what to compare before checking current product information.', ideas: ['This is a dated category guide, not a permanent endorsement of one product.', 'Check accessibility with your own device and access method.', 'Confirm privacy, price and feature claims at the provider before relying on them.'], activity: 'Compare two current options using access, cost, privacy and the job you need done.', checkpoint: 'You can explain why your preferred option fits this task and what current claim still needs confirmation.', caution: 'Product availability and features change.', estimatedMinutes: 10, reviewed: '5 August 2026' }));

export const taskLinks = [
  ['Choose an AI assistant', '02-choose-an-ai-assistant'], ['Get a better answer', '03-first-useful-conversation'], ['Find something useful AI can do', '04-everyday-things-ai-can-do'], ['Understand what kind of answer AI gives me', '05-know-what-you-are-holding'], ['Decide whether an answer is safe to use', '06-what-happens-if-it-is-wrong'], ['Check a factual answer', '07-check-an-answer'], ['Choose the right kind of image tool', '08-choose-an-image-tool'], ['Describe a photograph', '09-ask-for-an-image-description'], ['Double-check an image description', '10-check-an-image-description'], ['Read text in an image', '11-read-documents-forms-and-screenshots'], ['Understand a table, chart or presentation', '12-understand-tables-charts-and-slides'], ['Create an image', '13-create-your-first-image'], ['Check visual work without sight', '14-creative-control-without-sight'], ['Create a comic', '15-create-a-comic'], ['Make a video', '16-create-animation-and-video'], ['Publish visual work accessibly', '17-publish-visual-work-accessibly'], ['Understand AI models', 'models-and-open-weights'], ['Explore the philosophy of AI answers', 'philosophy-of-answer-shaped-objects'],
];
